apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: goserver-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    name: goserver # nome do Deployment a ser apontado
    kind: Deployment
  minReplicas: 3
  maxReplicas: 5
  targetCPUUtilizationPercentage: 30 # Referente a porcentagem maxima de uso da aplicação e gatilho para escalonar mais uma réplica